cache:
 mount:
    - /drone/.m2
build:
  main:
    image: maven:3-jdk-8-onbuild
    commands:
      - mvn clean install -Pcoverage -Dmaven.repo.local=/drone/.m2
      - echo "Build has been completed."
services:
   mysql:
    image: mysql:5.6.27
    environment:
      - MYSQL_DATATABASE =GOOGLE_API
      - MYSQL_USER = root
      - MYSQL_PASSWORD = 1990
