pipeline:
  build:
    image: maven:3-jdk-8
    mount:
      - repository
    commands:
     - if [ -d "/drone/repository" ]; then cp -a /drone/repository /usr/share/maven/ref ; fi
     - mvn -Ddocker.skip=true clean install
     - cp -a /usr/share/maven/ref/repository /drone